version: "3"
services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"

  rest:
    build: .
    environment:
      MONGO_URI: "mongodb://localhost:27017/?directConnection=true&serverSelectionTimeoutMS=2000"
      TWEET_FILE: "elonmusk.json"
#      INIT_SEED: 1
      PORT: "9000"
    network_mode: "host"
    depends_on:
      - db
    ports:
      - "9000:9000"

volumes:
  mongodata: